### ISSUE TITLE
Check TF Python API

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#1]
Check how Python calls Tensorflow under the hood - does it only use standard C API calls and everything is built on top of that or are there some custom / alternative solutions there that give it more features?

**Comment by radeusgd** [comment]
While working on this issue one may also read up about writing Python bindings in C.

**Comment by Swordlash** [comment]
After grepping tensorflow source directory for "c_api" pattern, I found that the following .py modules call c functions directly, all from tensorflow/framework (I omitted test files):
function.py
ops.py
importer.py
errors_impl.py
c_api_util.py
kernels.py
smart_cond.py

They all call c_api functions through pywrap_tensorflow.py, which is generated as a wrapper for C functions through SWIG framework. Moreover, it seems that Python API does not call any other C functions than those from pywrap_tensorflow.

**Comment by Swordlash** [comment]
Seems that TF uses SWIG for wrapping c_api calls from python directly.
