### ISSUE TITLE
Memory management utilities for interfacing with Luna

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#17]
We need to be able to extend shared_ptr lifetime for pointers that have been provided to Luna API and to decrease their refcount when Luna's GC frees them.

It would probably be implemented along with #16.
Should be based on https://github.com/luna/Dataframes/blob/master/native_libs/src/LifetimeManager.h

**Comment by wojtrz13** [comment]
I guess we can mostly copy LifetimeManager.h from Dataframes. We can probably change any-lite to std::any, as C++17 should work fine on Mac now: https://clang.llvm.org/cxx_status.html.

**Comment by radeusgd** [comment]
LifeTimeManager has a property (because of using std::any) that if you put in shared_ptr<T> you can only take out shared_ptr<T>.

Sometimes we put in shared_ptr<T> and get shared_ptr<U> where U is T's base class.
It's not possible with this architecture.
For now, we should always put the base class as it's most often taken out. If we ever need to also access the derived class some workaround or refactor will be required.

**Comment by radeusgd** [comment]
I think LifeTimeManager works so this can be closed. Any further issues with memory management shall probably get a separate issue.
