### ISSUE TITLE
Implement eval

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#20]
`def eval p :: P a -> Tensor a`

```
Tensor eval(OpBase& out) {
   create graph
   out.addToGraph
   runSession(outs=[out])
}
```

A helper function may be added to operations, like so:
```
class OpBase {
	virtual TF_Output* addToGraph(TF_Graph*, cached_map) = 0
}

class ConstOp {
	ConstOp(Tensor value);
	TF_Output* addToGraph(TF_Graph* g, cached_map) { 
               add new constant node to TF_Graph and set it value to one provided in constructor
         }
}

class Op {
	Op(string name, vector<shared_ptr<OpBase>> inputs);
	TF_Output* addToGraph(TF_Graph* g, cached_map) {
		for each i in inputs:
			node = if i in cached_map, get it, else i.addToGraph(...) and add it to cached_map
		add Op(name, nodes) to TF_Graph and return it
	}
}
```

**Comment by radeusgd** [comment]
We decided to use hashing for computation deduplication for now.

OpBase should have a hash() method. Hash value should be computed upon construction to keep computational complexity low.

**Comment by radeusgd** [comment]
First implementation should probably omit deduplication and once that works we should add it.

**Comment by wojtrz13** [comment]
In version 99fb516b4c1670e6ae9a50f860a6aeccd3b7bc23, when I run Main.luna for the first time, LifetimeManager threw an exception: "Cannot find storage for pointer 0x8b72f80 -- was it previously registered?" after printing a.toJSON and before printing c.toJSON in checkOp. It has not happened again so far and I haven't found out why it happened.

**Comment by wojtrz13** [comment]
It turns out that there are some issues with ManagedPointer: https://github.com/luna/luna/issues/212, to avoid them we have to use temporary variables when passing a function result as an argument when dealing with ManagedPointer, for example
```
managedPtr = ManagedPointer None . fromPointer releaseMethod arrPtr
ArrayWrapper managedPtr self.typename
```
rather than
```
ArrayWrapper (ManagedPointer None . fromPointer releaseMethod arrPtr) self.typename
```
