### ISSUE TITLE
Create Gradient

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#21]
Needs a `class Gradient : public OpBase` in C++ and corresponding Luna binding
```
class Gradient a:
	y, x :: a
for now x must be a scalar (Tensor of shape (1,), but we cannot ensure it statically yet)
```

**Comment by Swordlash** [comment]
Because we calculate a gradient of scalar with respect to another scalar, it would be better to call it a (partial) derivative.
