### ISSUE TITLE
Fix project structure - symlink required

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#24]
For now for Luna to detect `import Tensorflow` in `Main.luna` a symlink from `luna/stdlib/Tensorflow` to `local_libs/Tensorflow` *seems* to be required.

Maybe adding .luna_package will fix it?

**Comment by radeusgd** [comment]
Please specify the commit which resolves the issue (unless the commit mensions the issue in it's message).

**Comment by Swordlash** [comment]
Solved with commit https://github.com/Luna-Tensorflow/Luna-Tensorflow/commit/d8c687a7a7f7d99ec90dba919d3ef35b6249bf92
