### ISSUE TITLE
Implement deduplication

### ISSUE THREAD

**Issue by Swordlash** [Luna-Tensorflow/Luna-Tensorflow#28]
In our current graph model, many nodes, when reused, can be computed multiple times. To handle this issue, we have to implement deduplication, not to create nodes that are already in the graph, but to return those existing nodes.

**Comment by Swordlash** [comment]
Partially implemented with https://github.com/Luna-Tensorflow/Luna-Tensorflow/commit/78f98b9e4dffd52b9f42cf800c06f2f7b54cfff6, removed deduplication for consts.

**Comment by radeusgd** [comment]
I think we should describe why deduplication for consts has been removed.

For now, for example in differentiation, if you create a node 2*2, both `twos` are coerced to the same const instance which may be an issue for differentiation.
Deduplication for consts should definitely be readded after placeholders are implemented and can be used for this purpose, am I right?

**Comment by Swordlash** [comment]
Yes, after placeholders/variables are added, we can enable back deduplication of consts. In general, const is a const and two consts of the same value are mathematically the same objects, but in the current implementation consts also serve as variables, so we can't deduplicate them based on their values only.
