### ISSUE TITLE
Allow for creation of tensors of arbitrary shapes

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#43]
Our current implementation allows for 1d and 2d tensors, but arbitrary dimensionality should be supported.
However this should be done after #40

**Comment by wojtrz13** [comment]
Related commits: cbd44ad8c6a29196c3ced094a0a6e9e8c8b94059, 26b5d8fed3fb9652a5accca4f3ad6ed80a4f4e9f.
