### ISSUE TITLE
Create heterogenous graph eval

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#44]
For now batchEval works only with floats. It can be easily extended to work with any given type, but that wouldn't still be what we need.
A single graph instance (make_graph) should be able to handle outputs of various types, so we need a `add_output_TYPETAG` and evaluation shouldn't return just an array but a special EvalResult object with `get_output_value_TYPETAG` that will return output's values with the correct type.

**Comment by Swordlash** [comment]
The tensors produced by Graph.eval are given (on Luna side) typelabels provided by corresponding TFOutputs, like in the following code:
```tensors = (tensorwrappers . zip ((self . outputs) . map (x: x.typetag))) . each ((wrp, tag): Tensor (wrp tag))```
That way, the eval is, at least partially, heterogenous.

**Comment by radeusgd** [comment]
Is this issue considered done then? I think so. Otherwise, please reopen it.
