### ISSUE TITLE
Add other low level operations

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#48]
There are lots of operations in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt

Some generator should be written to create code for most of these operations.
For starters we want at least all the binary and unary numeric operations.

**Comment by Swordlash** [comment]
Many operations have different allowed argument types, for instance Transpose takes an argument of any tensor type and a second argument that is restricted to be of int type 1D tensor. Generator has to account for that.

**Comment by radeusgd** [comment]
Ok, I thought we may get away with a few FFI functions and do the rest generating Luna code, but it seems the right way might be to generate code for FFI as well, so that every operation has its FFI function.

**Comment by radeusgd** [comment]
We may erase types of operations in the C++ side of the API and only make sure types match in Luna side.

The generator should generate type signatures in comments and proper type assertions in function bodies.

**Comment by wojtrz13** [comment]
This has been dealt with in #7
