### ISSUE TITLE
Add error handling to FFI

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#61]
Currently all exceptions are uncaught and lead to interpreter's crash.
All FFI methods (all at least the ones that throw in reasonable cicrumstances) should be wrapped with code that catches the exception and sets a flag that caller's Luna code can read to signal an exception in a non-destructive way.

**Comment by wojtrz13** [comment]
Implemented in a31b85917fbe487a9f3095e49bc1b8dd87f78969.
