### ISSUE TITLE
RMSProp optimizer

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#85]

**Comment by radeusgd** [comment]
It turns out there are builting operations in Tensorflow for most of the optimizers, including RMSProp.
In that case we won't implement it ourselves but use these.
However they require their inputs to be TF_Variables, which we don't use due to our custom variable system, because of that we're going to rewrite the variable system to use the native ones, as in #87.

**Comment by radeusgd** [comment]
After #87 is finished what's left to be done is allocate proper variables with proper shapes and run the generated applyRMSPropGen operation for each trainable variable.

**Comment by Swordlash** [comment]
Resolved with commit 12f7db2.
