### ISSUE TITLE
Rewrite Variable system to use TF_Variables

### ISSUE THREAD

**Issue by radeusgd** [Luna-Tensorflow/Luna-Tensorflow#87]
It turns out there are builting operations in Tensorflow for most of the optimizers, however they require their inputs to be TF_Variables, which we don't use due to our custom variable system.
This task consists of rewriting the system so that we can use these Variables natively.

What needs to be done:
- split evaluation to 3 phases
  + initialize variables from State
  + run main graph
  + read new variable values and update them in State
- change Variable to use native Variable handle
- remove assign as it can be emulated with native assign generated operation
- add a computation sequencing mechanism `>>`/`seq` (actually rewrite our assign into this)
   + it should take 2 outputs and return the first output, but also make sure the second one has been evaluated, thus we can use some computations only for their side effects by sequencing them with this mechanism

**Comment by radeusgd** [comment]
Make sure putting into Target operations:
- something already fetched in outputs
- something without sideeffects (a pure node like Add)
doesn't cause errors

**Comment by wojtrz13** [comment]
Note: putting into target operations things that have no side effects or are already fetched causes no problems in TensorFlow C API.

**Comment by radeusgd** [comment]
Variables are almost working.
Next step is to implement the sequence operator (it's done on C++ side, only Luna wrapper is missing).
There's some issue with classification (crash), not sure if related to new variables - needs investigation.
Also one line in vartest stopped compiling, but due to it being turned off for a moment, can't pinpoint when the regression happened - small fix needed.
